version: "3.8"

services:
  efishery-postgres:
    container_name: efishery-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=efishery_commerce
    networks:
      - api
  efishery-api:
    container_name: efishery-api
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=efishery-postgres
      - DB_PORT=5432
      - DB_DATABASE=efishery_commerce
    depends_on:
      - efishery-postgres
    networks:
      - api
networks:
  api:
    driver: bridge
